- hosts: "{{ target_hosts | default('localhost') }}"
  become: yes
  become_user: root

  tasks:
    - name: rate limit var
      shell: cat {{ input_file }} | shyaml get-value info.rate-limit
      register: nginx_include_rate_limit
    - set_fact:
        rate_limit_var: "{{ nginx_include_rate_limit.stdout }}"
    - debug: var=rate_limit_var
    - name: update rate limit
      lineinfile:
        path: "{{ input_file }}.conf"
        insertafter: 'location = /_drivers-api'
        line: 'limit_req zone=mylimit;'
      when: rate_limit_var == true
