- hosts: "{{ target_hosts | default('localhost') }}"
  become: yes
  become_user: root

  tasks:
    - name: build snippet from swagger
      shell: ./swagger_to_conf.sh -l -u {{ upstream_ip }} {{ input_file }} | grep -v shyaml
      register: nginx_snippet
    - debug: var=nginx_snippet.stdout
    - set_fact: config_snippet={{nginx_snippet.stdout}}
    - name: replace config
      template:
        src: api-gateway.j2
        dest: "{{ input_file }}.conf"
      delegate_to: localhost
    - name: JWT var
      shell: cat {{ input_file }} | shyaml get-value info.rate-limit
      register: nginx_include_jwt
    - set_fact:
        rate_limit_var: "{{ nginx_include_jwt.stdout }}"
    - debug: var=rate_limit_var
    - name: update global rate limit
      lineinfile:
        path: "{{ input_file }}.conf"
        regexp: '^#<global_rate_limit>'
        line: 'limit_req_zone $binary_remote_addr zone=mylimit:10m rate=1r/m;'
      when: rate_limit_var == true
